### ISSUE TITLE
Wrong length for compacted heightmap with 1.16.1

### ISSUE THREAD

**Issue by ThuverX** [jglrxavpok/Hephaistos#3]
I tried loading a 1.16.1 world, and gave this error:
```java
org.jglrxavpok.hephaistos.mca.AnvilException: Wrong length for compacted heightmap
        at org.jglrxavpok.hephaistos.mca.Heightmap.<init>(Heightmap.kt:15)
        at org.jglrxavpok.hephaistos.mca.ChunkColumn.<init>(ChunkColumn.kt:70)
        at org.jglrxavpok.hephaistos.mca.RegionFile.readColumn(RegionFile.kt:149)
        at org.jglrxavpok.hephaistos.mca.RegionFile.access$readColumn(RegionFile.kt:23)
        at org.jglrxavpok.hephaistos.mca.RegionFile$getChunk$1.apply(RegionFile.kt:98)
        at org.jglrxavpok.hephaistos.mca.RegionFile$getChunk$1.apply(RegionFile.kt:23)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk(RegionFile.kt:98)
        at org.corbellumteam.mmo.World.AnvilChunkLoader.loadMCA(AnvilChunkLoader.java:62)
        at org.corbellumteam.mmo.World.AnvilChunkLoader.loadChunk(AnvilChunkLoader.java:51)
        at net.minestom.server.instance.InstanceContainer.retrieveChunk(InstanceContainer.java:430)
        at net.minestom.server.instance.InstanceContainer.loadOptionalChunk(InstanceContainer.java:307)
        at net.minestom.server.entity.Player.setInstance(Player.java:577)
        at net.minestom.server.entity.EntityManager.waitingPlayersTick(EntityManager.java:40)
        at net.minestom.server.entity.EntityManager.updateWaitingPlayers(EntityManager.java:22)
        at net.minestom.server.UpdateManager.lambda$start$0(UpdateManager.java:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
This was using a freshly generated 1.16.1 world, with just a few chunks loaded.

The region files I used:
[region.zip](https://github.com/jglrxavpok/Hephaistos/files/5037013/region.zip)

**Comment by jglrxavpok** [comment]
Started working on 1.16 support on branch 1.16-support

**Comment by jglrxavpok** [comment]
v1.0.5 added 1.16 support and your file is openable with Hephaistos (see src/test/java/regression/issue_3)
