### ISSUE TITLE
Error when reading mca version 1.12.2

### ISSUE THREAD

**Issue by CoolLoong** [jglrxavpok/Hephaistos#34]
```
org.jglrxavpok.hephaistos.mca.AnvilException: Missing field named 'Status' (or of wrong type)
	at org.jglrxavpok.hephaistos.mca.AnvilException$Companion.missing(AnvilException.kt:15)
	at org.jglrxavpok.hephaistos.mca.readers.ChunkReader.getGenerationStatus(ChunkReader.kt:62)
	at org.jglrxavpok.hephaistos.mca.ChunkColumn.<init>(ChunkColumn.kt:125)
	at org.jglrxavpok.hephaistos.mca.RegionFile.readColumn(RegionFile.kt:185)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk$lambda-3(RegionFile.kt:111)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk(RegionFile.kt:111)
```

**Comment by jglrxavpok** [comment]
Sorry but 1.12.2 is not supported by Hephaistos. The library only supports versions > 1.15.
If you want to use a 1.12.2 world, convert it via the game directly before using it in Hephaistos.
