### ISSUE TITLE
Error When Reading a Region File

### ISSUE THREAD

**Issue by JanCantCode** [jglrxavpok/Hephaistos#39]
Im trying to read a region file taken from a vanilla 1.20.1 singleplayer world using 

```java
RandomAccessFile randomAccessFile = new RandomAccessFile("C:\\Users\\itsja\\PlayerDataReader\\src\\main\\resources\\worlddata\\r.0.0.mca", "rw");
        RandomAccessFileSource source = new RandomAccessFileSource(randomAccessFile);
        RegionFile regionFile = new RegionFile(source, 0, 0);
        ChunkColumn column = regionFile.getChunk(16, 16);
```

But this results me in 
``Exception in thread "main" org.jglrxavpok.hephaistos.mca.AnvilException: Missing field named 'Level' (or of wrong type)
	at org.jglrxavpok.hephaistos.mca.AnvilException$Companion.missing(AnvilException.kt:15)
	at org.jglrxavpok.hephaistos.mca.ChunkColumn.<init>(ChunkColumn.kt:71)
	at org.jglrxavpok.hephaistos.mca.RegionFile.readColumn(RegionFile.kt:183)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk$lambda-3(RegionFile.kt:109)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk(RegionFile.kt:109)
	at org.example.WorldReader.main(WorldReader.java:21)
``. Is this something I can fix?

**Comment by JanCantCode** [comment]
mca file in question can be downloaded here (github does not allow me to upload .mca ..) https://workupload.com/file/VFCXtSPTV6C

**Comment by JanCantCode** [comment]
Turns out I was using an outdated version of hephaistos, I had assumed the newest github release (2.2.0) would be equivalent to the newest version which could be obtained from anywhere else, altho 2.6.1 can be obtained from maven.
